### ISSUE TITLE
caching api with different post payload 

### ISSUE THREAD

**Issue by matt212** [kwhitley/apicache#113]
Hi, 
can we cache an single api with different post payload basically paginate apis scenario with  pagnum and pagesize 
like for e.g : 10 request each request contains 20 recordset for totalcount for 200 records !

**Comment by kwhitley** [comment]
sure... by default the query string is included in the cache key, so these requests would be cached as two unique entries:

```
/api/books/all?page=1
/api/books/all?page=2
```

If that doesn't work, or you use something other than the query string to differentiate (e.g. something you've set in the response), you can use the `appendKey` option.

That answer your question?

**Comment by matt212** [comment]
thank you for clarification @kwhitley  !
How to implement appendkey in post method 
Please refer higlihighted section in below screenshot !
![mehs](https://user-images.githubusercontent.com/1698139/30700285-cc44a3dc-9f04-11e7-944d-68069324f1b4.png)


something like this 
apicache.options({ appendKey: ['pageno', 'pageSize'] })
which throws error !
any pointers on how to implement appendkey for my post method case scenario

**Comment by kwhitley** [comment]
Currently the implementation takes an array of the path nodes to a single request param.

Because this has been an ongoing request and to allow for true flexibility, I'm modifying the appendKey option to also take a `function(request, response)` and return a string/value.  Then you could simply use the following option:

```js
{
  appendKey: (req, res) => req.pageSize + ',' + req.pageno
}
```

That work?  I've just implemented the code and tests, and am updating the README.  Will roll out today as v1.1.0.

**Comment by matt212** [comment]
@kwhitley  thank you so much man 
so final  codebase should look like this after new update as of v1.1.0. 

```
const apicache  = require('apicache')
const cache     = apicache.middleware
apicache.options({appendKey: (req, res) => req.pageSize + ',' + req.pageno })
router.post('/api/searchtype/', cache('1 minutes'), authfunctions.validateAccesstoken, function(req, res) {
req.apicacheGroup = req.params.collection
 var number_of_items = req.body.pageno;
    var pageSize = req.body.pageSize;
})
```
Any recommendations,pointers  ?

**Comment by kwhitley** [comment]
No prob @matt212 

You can drop the `req.apicacheGroup = req.params.collection` as you don't seem to be using any req params.  That would apply when you have a route like `/api/:collection` or something.

If the pageSize and pageno are in the request.body rather than the request itself, you'll need to modify that appendKey function to be `(req, res) => req.body.pageSize + ',' + req.body.pageno`.  Just test it both ways.  If you want to see how it's cached, add a route to expose the apicache index while debugging:

```js
router.get('/api/cache', (req, res) => {
  res.json(apicache.getIndex())
})
```

You should see the keys, etc being populated there as you hit routes.

**Comment by matt212** [comment]
i am getting below error 

![error](https://user-images.githubusercontent.com/1698139/30705122-384d5684-9f12-11e7-946a-285a5f4c3746.png)

updated codebase !
```
const apicache  = require('apicache')
const cache     = apicache.middleware
apicache.options({appendKey: (req, res) => req.body.pageSize + ',' + req.body.pageno })
router.post('/api/searchtype/', cache('1 minutes'), authfunctions.validateAccesstoken, function(req, res) {

 var number_of_items = req.body.pageno;
    var pageSize = req.body.pageSize;
})
```

**Comment by kwhitley** [comment]
you'll need v1.1.0 to test that... (it's now on NPM)

**Comment by matt212** [comment]
It worked man thanks ! 
can we do the same with different payload parameters like 

`apicache.options({appendKey: (req, res) => req.body.pageSize + ',' + req.body.pageno+ ',' + req.body.searchparam  })`

**Comment by kwhitley** [comment]
You can use anything you like in that function (in addition to anything within the request/response objects)...  it just needs to return something that is easily converted to string (as the key is currently string format)

```
// more elaborate example
apicache.options({
  appendKey: (req, res) => req.method + res.session.id + (new Date).getMonth()
})
```

**Comment by matt212** [comment]
Hi @kwhitley , 
I am unable to cache my GET request , what seems to missing from below configuration

```
const apicache  = require('apicache')
const cache     = apicache.middleware
router.get('/getempdetails/:pageno', cache('1 minutes'), authfunctions.isauth, function(req, res) {
console.log("pagenumber"+req.params.pageno);
res.end()

});
```
even with constant url like 
![ms](https://user-images.githubusercontent.com/1698139/30737344-de342a46-9fa3-11e7-9b8c-410fbca79b19.png)

**Comment by chla** [comment]
Can I just do this?

const apicache = require('apicache');
const cache = apicache.middleware;

apicache.options({appendKey: (req, res) => req.body && JSON.stringify(req.body)});
router.post('/api/searchtype/', cache('1 day'), cms.getPost);

module.exports = router;
