### ISSUE TITLE
Proper way of setting custom cache keys ?

### ISSUE THREAD

**Issue by stanislasdrg** [kwhitley/apicache#116]
Hello I am trying to set custom cache keys in a POST endpoint.
I had a look at the documents, which recommend to do it [that way](https://github.com/kwhitley/apicache#custom-cache-keys).

I therefore put the config in a module :

```
module.exports = {
  cache: apicache
        .options({
          redisClient: redis.createClient(redisConnectionString),
          duration:  '1 month',
          appendKey: (req) => req.body.search_terms,
          statusCodes: {
            exclude: [],    // list status codes to specifically exclude (e.g. [404, 403] cache all responses unless they had a 404 or 403 status)
            include: [200], // list status codes to require (e.g. [200] caches ONLY responses with a success/200 code)
          }
        })
        .middleware
}
```

And called that config within my endpoint : 

```
myRouter.route('/my/route')
                .post(
                	middleware.params('search_terms', 'multi_domain'),
                        redis.cache(),
                	myFunkyFunc(),
                	middleware.send
              	);
```

Unfortunately the appended key is undefined, even if I receive the POST params properly.
I am unsure how the req and res object are passed to the apicache object itself. I suppose it's following Express' middleware function flow. In that case, what am I doing wrong here ? 

Thanks!

**Comment by kwhitley** [comment]
Sorry for the much delayed response on this @stanislasdrg, I've been wrapped up for months in a huge research project...

So I'm not exactly sure what you're doing there, or with what framework (as it doesn't match the Express routing signature).  Assuming the first bit (your module.exports), the "cache" attribute is actually the undefined middleware.  By simply calling the function, with or without a duration/local-options via `middleware('1 minute')` or `middleware()`, it now turns into a valid valid middleware with (request, response) params as inputs.

For your example, again assuming the first cache config as an external file (and Express for my own familiarity):

```js
import express from 'express'
import { cache } from './my-cache-config-file' 
/* 
  cache is now the UNFORMED middleware function, waiting to be called  
  with a duration (or none to use the internal option as set by `defaultDuration`)
*/

let useCache = cache() // this executes the preformed middleware, turning it into ACTUAL middleware

let app = express()

app.post('/my-post-route', useCache, (req, res) => {
  res.send('something')
})
```

A couple notes... use `defaultDuration` rather than `duration` in the config (per docs), and if you want to skip the executing step on the middleware function in your files, simply execute in your external file (so the formed middleware is the export, rather than the unformed one).

Example:
```js
module.exports = {
  cache: apicache
        .options({
          redisClient: redis.createClient(redisConnectionString),
          defaultDuration:  '1 month', // corrected
          appendKey: (req) => req.body.search_terms,
          statusCodes: {
            exclude: [],    // list status codes to specifically exclude (e.g. [404, 403] cache all responses unless they had a 404 or 403 status)
            include: [200], // list status codes to require (e.g. [200] caches ONLY responses with a success/200 code)
          }
        })
        .middleware() // executed
}
```

Hope this helps!  If you still have issues, feel free to re-open!
