### ISSUE TITLE
monkey patch res.write instead of res.send

### ISSUE THREAD

**Issue by mkoryak** [kwhitley/apicache#12]
`res.send` is an express method that calls `res.write` and `res.end` which are node http method. You should monkey patch `res.write` so that your lib  works without express. 

You might also look into supporting chunked encoding, check out this impl:
http://www.senchalabs.org/connect/compress.html

**Comment by acanimal** [comment]
+1 
I think making middleware compatible both with express/connect would be awesome.
I'm working on a project where apicache would be a great solution (see https://github.com/acanimal/clyde). Currently I'm workin on a so called *filter* to cache responses based on node-cache, but apicache would be a direct solution.

Thanks

**Comment by kwhitley** [comment]
Sorry for the delay @mkoryak @acanimal, I work in Kuwait which has tied up my life lately - if one of you wants to test this and submit a PR, I'd be happy to merge!

**Comment by acanimal** [comment]
I'll try to get some time and make a PR. A few days ago I just made something similar (https://github.com/acanimal/clyde-memory-cache/blob/master/lib/index.js).

Cheers

**Comment by acanimal** [comment]
@kwhitley Can you assign me this tiquet?

**Comment by kwhitley** [comment]
@acanimal gladly! :+1:

**Comment by kwhitley** [comment]
Any present-day interest in completing this?  I have a branch open for this, but I'm not sure the demand for connect support these days...

**Comment by piggyslasher** [comment]
Any updates on this guys?? Thanks.

**Comment by kwhitley** [comment]
@piggyslasher is the use case because you use connect/raw-node or what?

This is on my short list but it's actually not a trivial rewrite, so I want to make sure the effort is warranted!

**Comment by kwhitley** [comment]
**Update:** @mkoryak @acanimal @piggyslasher This is about to roll out in next minor release (finalizing now, have test suite mostly passing, then cleanup of all old refs)

The change is big, but probably a lot more robust (allows for caching of any type of response because headers are never implicitly set by apicache, but rather cloned from the original response):

### Changes
I hijack `res.end(data, encoding)` instead of `res.send()` - as this is called once, and only once at the end of all responses, I copy the data passed in (Buffer as far as I'm seeing), the existing headers (plus a couple apicache-specific ones, and the statusCode.  This is used to rebuild the original response for cache intercepts later, which are also sent via `res.writeHead(statusCode, headers)` then `res.end(data, encoding)`

This allows for all the sugar methods like `res.json()` `res.jsonp()` `res.send()` etc to continue to function, set headers, etc without affecting the operation of apicache.

**Comment by mkoryak** [comment]
I love it when my ancient issues get closed. I think this is a good thing 👍
