### ISSUE TITLE
Modify response to http 304 status

### ISSUE THREAD

**Issue by a-cabinti** [kwhitley/apicache#131]
Hi,

I have a question.
Is there a possibility to modify the http status to 304 when the response data is from cache? 

Thanks in advance :)

**Comment by julbra** [comment]
This would be incorrect. A 304 response implies that the response was not modified compared with what the client (e.g. browser) already has in its local cache. A 304 response doesn't send back the body and is thus only suitable when the client requests the resource with particular headers set such as `If-None-Match: <etag>` and `If-Modified-Since: <date>`

**Comment by kwhitley** [comment]
@a-cabinti, @julbra is correct - this is all handled anyway, and once you implement apicache, and refresh your client-side pages, you'll notice resources automatically getting 304 responses.
