### ISSUE TITLE
Can I cache request have the same payload only?

### ISSUE THREAD

**Issue by kieusonlam** [kwhitley/apicache#133]
I have a api get data by payload (req.body), then is there anyway I can cache the request with the same payload only?

**Comment by chrisdeely** [comment]
I believe you could achieve this using the `appendKey` method to generate a custom cache key. See the docs [here](https://github.com/kwhitley/apicache#custom-cache-keys).

Your best bet would probably be to hash the `req.body` through some routine like base64, MD5, SHA, etc to generate a short value which will be unique to the payload value.

**Comment by kwhitley** [comment]
Thanks for jumping on the response @chrisdeely - you're absolutely correct!

@kieusonlam apicache can take a custom appendKey function [option] with the following signature:
```js
appendKey(req, res)
```

As you can see, it has full access to both the request and the response objects in order to generate a key however you see fit.  As @chrisdeely mentions, your best best may be to hash the entire req.body and return that as the key.

```js
// example config
{
  appendKey: (req, res) => somehashfunction(req.body)
}
```

Hope that helps!  Let me know if you have issues with this and I'll reopen...
