### ISSUE TITLE
Header exposing npm module name and store used.

### ISSUE THREAD

**Issue by satya-jugran** [kwhitley/apicache#144]
The below lines in file apicache.js are exposing couple of critical information to the www. 
1. It is exposing that apicache is being used at server.
2. If redis is used with it, It is exposing that redis is being used at server.

`      'apicache-store': globalOptions.redisClient ? 'redis' : 'memory',	
      'apicache-version': pkg.version`

These headers should be removed. If not, atleast there should be a production check before assigning any additional module specific headers.
Something like: 
`if (process.env.NODE_ENV !== "production") {
      
}`

**Comment by smddzcy** [comment]
I agree with putting a production check. They're good for debugging purposes, but they shouldn't be public.

**Comment by adamelliotfields** [comment]
Came here to express the same concern. It's a common practice to prevent the language/framework of the server app from being shared to the client. By exposing that you're using `apicache`, you're telling potential attackers that you're running  a Node server most likely with Connect/Express.

A quick workaround would be to add some middleware AFTER apicache to remove headers (I haven't tried this yet - at work):

```javascript
// Assuming Express
res.removeHeader('apicache-store');
res.removeHeader('apicache-version');
```

This should be a quick PR otherwise though. Agree with using the production environment variable approach.

**Comment by kwhitley** [comment]
Got it - will implement a test and (at least) leave headers off on `NODE_ENV === 'production'`

**Comment by adamelliotfields** [comment]
Thanks Kevin! Great library BTW 😄

**Comment by satya-jugran** [comment]
> Got it - will implement a test and (at least) leave headers off on `NODE_ENV === 'production'`

Awesome, Thanks! :)
