### ISSUE TITLE
Recentry added cache performance track is causing high memory usage

### ISSUE THREAD

**Issue by julianpoma** [kwhitley/apicache#174]
With the recently added cache performance tracking, we are experiencing very high memory usage on our apps, which run on T2 Micro on AWS.

This option should be enabled globally with an option.

BTW, the cache index is also being stored on memory when using redis.. This is inconvenient when using a load balancer.

**Comment by kwhitley** [comment]
Thanks all for working on this... @svozza @killdash9 anyone want to weigh in here?

## Options Foward
1. set `{ trackPerformance: false }` as default to prevent automatically (and negatively) impacting others as they update their deps.  This is technically a breaking change, only for those few that have implemented features around performance tracking already (very new feature, so probably only a few)... **but while semantically correct to do so, I'd prefer to not to major version bump** (because of the impact of new versions, the fact that there are real milestones slated for v2, etc).  Thoughts on doing this approach?
2. set `{ trackPerformance: true }` to maintain complete compatibility with previous release.  This avoids breaking semver, but could negatively impact a huge number of users...

For the record, I'm leaning towards option 1.  Conversely, what I **could** do is to turn trackPerformance to true whenever `getPerformance()` method is called.  This would drop some initial unlogged performance before the request, but ensure that anyone that's actually using it at least gets it turned on automatically somehow.

**Comment by killdash9** [comment]
I'd say make performance tracking disabled by default.  I'm sure very few are using this feature currently.

**Comment by kwhitley** [comment]
Alright guys, thanks for your patience and understanding on this, and thanks @fernandolguevara for the quick fix!  This is patched as of `1.5.2` with default behavior of `{ trackPerformance: false }`.  Tests have been updated to reflect, including testing performance tracking when turned on.

- **Sidenote**: Also released in `1.5.2` are fixes for the deprecation notices regarding `Buffer` and `response._headers`
