### ISSUE TITLE
Support caching other data types besides JSON

### ISSUE THREAD

**Issue by nmors** [kwhitley/apicache#49]
I was thinking, it may be a good idea to add support for binary or other types, rather then only JSON. 

Redis claims to have good support for binary types, (see http://redis.io/topics/data-types) so that would mean that endocding/decoding would be unnecessary

We would also need a mechanism to store the mime-type (edit:) / `Content-Type` header

**Comment by kwhitley** [comment]
So @nmors, as of 0.5.0 it's currently intercepting `response.end` which is transferring a `Buffer` type.  I cache the entire buffer, including the encoding type, in order to recreate the original response, and recreate the cloned headers.

I'd love some help testing it out, but as it stands, I think right now it should be able to work with any content type at all, certainly no longer just JSON.  I'll start adding tests to confirm (unless you want to add some of course, lol)
