### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by rdewolff** [kwhitley/apicache#56]
Hello all

We are starting to use apicache in dev and really like it.

Am wondering if anyone has done some memory usage analyses on production environment ? I would be glad to see your results if you have.

Thanks for sharing!

**Comment by kwhitley** [comment]
@rdewolff I haven't done/seen memory benchmarks on this, but it should be relatively light as it only stores the data and headers of requests - then auto expires them internally after the listed length of time.  For small APIs this is generally safe except against scripted attacks that can fill up the cache with repeated cache-busting requests (e.g. someurl.com/api/?foo=AgFxSE).

For production, I'd recommend the following:

1. Only enable caching on success hits (rather than caching every miss):
```js
  import apicache from 'apicache'
  
  const onlySuccesses = (req, res) => res.statusCode === 200
  let cacheOnSuccess = apicache.middleware('1 week', onlySuccesses)

  app.get('/api/endpoint', cacheOnSuccess, (req, res) => {
    // do something
  })
```

2. Use with redis - this will allow you to configure memory limits, shard, persist cache between instance resets, etc.  I'd highly recommend this, and as I don't personally use it with redis (aside from a few unit tests to support it), I'd love someone putting it through its paces in a production redis environment - I'll be more than happy to sort out any issues that come up with it (or accept PR fixes)
```js
  import redis from 'redis'
  import apicache from 'apicache'

  apicache.options({ redisClient: redis.createClient() })

  // all usage remains the same
```

**Comment by kwhitley** [comment]
I will say this - although we use it extensively on live production apps with no problems (and it's always the first thing added to any API delivery project, gateway, etc), a recent change that enables caching of most content types (vs its original implementation that forced json/jsonp formats), has a known issue when gzip compression is enabled via middleware in express (based on the response method i'm patching).  I'm still working on that, but many people enable compression via a proxy layer anyway (Apache, NGINX, etc), and that should still be fine.

**Comment by rdewolff** [comment]
Thanks for the nice and prompt answer @kwhitley ! Maybe we'll give redis a try, that's a good idea. If I find some time when we go live in Q1/2017 I might check the memory usage a bit closer and if I get any good reports or interesting data I'll post here.

Cheers!
