### ISSUE TITLE
appendKey fails if req.session.id not set

### ISSUE THREAD

**Issue by timelf123** [kwhitley/apicache#67]
Trying to use appendKey in my app `appendKey:  ['user', '_id']` -- but `req.user` is not set unless the user is logged in. This causes the middleware to throw `TypeError: Cannot read property '_id' of undefined  at Layer.cache (apicache.js:296:32)`

I'd expect the default behavior to be - append with nothing if key not available
https://github.com/kwhitley/apicache/blob/master/src/apicache.js#L292-L299

**Comment by hyperh** [comment]
+1 I would expect the behavior OP described.

Another way I think would be good, is if the `appendKey` option let you use a custom function to manipulate the `req` object to make a very customized key, rather than a simple object field lookup.

To get around this I made 2 `apicache` instances. One for public routes (user not signed in yet), one for private routes (expects `req.user.id` to exist).

**Comment by kwhitley** [comment]
Agreed regarding the limitations of the overly simplified current appendKey implementation - v1.0.0 will definitely have custom function support, if not before.

**Comment by kwhitley** [comment]
Closing this - v1.x will have a function override for creating (very) custom keys
