### ISSUE TITLE
Middleware toggle

### ISSUE THREAD

**Issue by IgorKhromov** [kwhitley/apicache#80]
Hi! I have some question, mb i didn't understand something.
```
const onlyStatus200 = (req, res) => res.statusCode === 200

const cacheSuccesses = cache('5 minutes', onlyStatus200)

app.get('/api/missing', cacheSuccesses, (req, res) => {
  res.status(404).json({ results: 'will not be cached' })
})
```
```
  this.middleware = function cache(strDuration, middlewareToggle) {
    var duration = instance.getDuration(strDuration)

    return function cache(req, res, next) {
      function bypass() {
        debug('bypass detected, skipping cache.')
        return next()
      }

      // initial bypass chances
      if (!globalOptions.enabled) return bypass()
      if (req.headers['x-apicache-bypass'] || req.headers['x-apicache-force-fetch']) return bypass()
      if (typeof middlewareToggle === 'function') {
        if (!middlewareToggle(req, res)) return bypass()
      } else if (middlewareToggle !== undefined && !middlewareToggle) {
        return bypass()
      }
```
So onlyStatus200 middleware is called before we have some operations with response. And it would be always 200 as initial, so actually all statuses would be cached.
Option statusCodes: [ include: [200] ] works as should.
Thanks.

**Comment by kwhitley** [comment]
@IgorKhromov Remember, the cache middleware (including toggle middleware shown here) gets called at the last moment, before `res.end`, rather than at the entry to the route like typical middleware (it does this by hijacking the `res.end` to delay its execution).  By this point, you would have set 403, 404, 500 statuses depending on the response.

This particular middleware toggle simply returns true if the statusCode === 200, so if that returns true, the middleware continues on to cache the response.

That help at all?  Test it out by setting the statusCode to say, 400 within your route and see if it caches.  It shouldn't!  If it does, please reopen this as a bug and I'll resolve and add test coverage.

Cheers!

**Comment by caprica** [comment]
I think I'm also missing something here...

    const router = require('express').Router()

    const apicache = require('apicache')
    const cache = apicache.middleware

    const statusOkOrNotFound = (req, res) => {
        console.log("check status " + res.statusCode)
        return res.statusCode === 200 || res.statusCode === 404
    }

    const cacheValid = cache('5 minutes', statusOkOrNotFound)

    router.get('/api/test', cacheValid, (req, res) => {
        console.log("API request, send fake error")
        res.status(500).send("fake error")
        return
    }

When I execute this request, I see this trace in unexpected order:

    check status 200
    API request, send fake error

And this response:

    HTTP/1.1 500 Internal Server Error
    x-powered-by: Express
    cache-control: max-age=300

The only difference I see between this and your example is I do:

    const router = require('express').Router()
    router.get(...)

And your example shows:

    const app = require('express')
    app.get(...)

**Comment by kwhitley** [comment]
Hmmm. That's because the middleware toggle is executed before your route logic. It's 200 at the time of evaluation, then gets set to 500 just before final send. I'll have to give some thought to the best solution around this behavior!

~ Kevin @krwhitley.com
On Mon, Jul 31, 2017 at 4:49 AM, Mark Lee <notifications@github.com> wrote:
I think I'm also missing something here...

const router = require('express').Router()

const apicache = require('apicache')
const cache = apicache.middleware

const statusOkOrNotFound = (req, res) => {
    console.log("check status " + res.statusCode)
    return res.statusCode === 200 || res.statusCode === 404
}

const cacheValid = cache('5 minutes', statusOkOrNotFound)

router.get('/api/test', cacheValid, (req, res) => {
    console.log("API request, send fake error")
    res.status(500).send("fake error")
    return
}


When I execute this request, I see this trace in unexpected order:

check status 200
API request, send fake error


And this response:

HTTP/1.1 500 Internal Server Error
x-powered-by: Express
cache-control: max-age=300


The only difference I see between this and your example is I do:

const router = require('express').Router()
router.get(...)


And your example shows:

const app = require('express')
app.get(...)

**Comment by sdomagala** [comment]
I'm having the same issue, check is triggered long before the call is done - therefore it caches every response

```
node -v
v6.10.3
npm -v
3.10.10
```
