### ISSUE TITLE
Function gets called on every request if all requests are 304

### ISSUE THREAD

**Issue by TrevorDev** [kwhitley/apicache#87]
Using code:
```
app.get('/api/collection/:id?', cache('5 minutes'), (req, res) => {
  console.log("hit")
  res.json({ foo: 'bar' })
})
```

1. start server
2. load page in browser
3. hit refresh
4. observe hit is only outputted at most every 5 minutes as expected
5. stop server but keep browser open
6. start server
7. hit refresh on browser
8. observe on every refresh, hit is outputted which is not expected

Apicache overwrites the res.end and res.write methods in makeResponseCacheable in apicache.js but these methods are called with empty string as content when response is 304 but hit is still displayed. Is there anyway to workaround this?

**Comment by kwhitley** [comment]
Thanks for the writeup @TrevorDev - sorry for the long delayed response!  Will look into this shortly...

**Comment by Geczy** [comment]
Same issue here, would be nice to know how to workaround while you're looking into it...

**Comment by STEVEOO6** [comment]
You should be able to use the following header override as a workaround in the meantime.

`
const cache = apicache.options({
  headers: {
    'cache-control': 'no-cache, no-store, must-revalidate'
  }
}).middleware
`

**Comment by RowanMeara** [comment]
I believe this occurs because apicache uses res.end to create the object that is inserted.  Although I am not an expert on express, I believe that on a cache miss, apicache calls the next middleware which leads to express turning the response turning into a 304 response.  Therefore, when the end function is called, express has removed the content so there is nothing to cache.

**Comment by kwhitley** [comment]
The explanation @RowanMeara gives appears to be spot on... tracking carefully through this (thanks for the detailed writeup of how to replicate this btw), I can see that apicache is (after restarting the server), in fact determining that the new requests/responses should be cached, but the content sent to `res.end(content)` is removed by express, not allowing apicache to actually create a cache entry...

A force refresh (Ctrl/Cmd+Shift+R in Chrome) will kick it back through the system and get the entry cached again...

So without an explanation of why express removes the content, or how to prevent this behavior, I'm going to close this issue for now, as it appears to be out of the scope of apicache - and rather an unfortunate side-effect.

If **anyone** @TrevorDev @STEVEOO6 @Geczy @svozza (like how I threw you in on this one? ;) has an idea on how to safely resolve this without changing the core/default apicache behavior, please let's re-open and discuss!

**Comment by TrevorDev** [comment]
I forget how I resolved this a long time ago, i think I used the https://github.com/tdebarochez/connect-cache library or wrote my own caching logic.

**Comment by kimabrandt** [comment]
> So without an explanation of why express removes the content, or how to prevent this behavior, I'm going to close this issue for now, as it appears to be out of the scope of apicache - and rather an unfortunate side-effect.

@kwhitley Maybe you could monkey-patch the express `res.send`-function, which [seams to remove/override the body/content/chunk when encountering a `204 No Content` or `304 Not Modified` response](https://github.com/expressjs/express/blob/master/lib/response.js#L213). Inside this monkey-patch, you'd only need to make a backup/copy of the body/content/chunk, since [the `res.end`-function is called at the end](https://github.com/expressjs/express/blob/master/lib/response.js#L221), which should work with the existing apicache-logic!?
